### PR TITLE
Add a windows 32 bit python3.8 wheel build of 7.43.0.3

### PR DESCRIPTION
**Pull request by matteius**
I built this on a new notebook computer with Windows 10 and Ryzen 5 CPU/chipset.   I used the vcdist and MS2017 build tools to get my libcurl.lib dependency.   I am not sure why the file size of my whl is smaller than some of the past versions, however worth posting and trying to gather feedback on my effort.

### CODE REVIEW

**Comment by matteius** [comment]
If this gets merged, how will these and the existing whl file for 3.7 get uploaded to pypi?  Pypi doesn't have the one existing whl file from here already.

**Comment by p** [comment]
Thank you for the patch, how were these wheels tested?

**Comment by matteius** [comment]
@p  Truthfully they were not tested other than they could be installed, until you asked the question and then this morning I ran into the following issue:  the .whl file I built has a lightweight .pyd file that doesn't include the libcurl .dll files statically linked (must have been dynamically linked somehow) and so when I tried to run locally I had to copy over the relevant files out of tools/curl for the build architecture 32 vs 64 bit.  Since I couldn't figure out this AM how to get them to statically link, I updated the PR to include zip files for both build trees 32 and 64 bit of curl using windows 10 and vcpkg.

**Comment by p** [comment]
Correct me if I'm wrong but those zip files won't help users who type `pip install pycurl`.

**Pull request closed without merging**
